### ISSUE TITLE
`x[i]` should be replaced with `x2[i]`, and so on and so forth

### ISSUE THREAD

**Issue by CGMossa** [MoseleyBioinformaticsLab/visualizationQualityControl#22]
https://github.com/MoseleyBioinformaticsLab/visualizationQualityControl/blob/5522fa8e1c3328be11a28f0b67f73e08e078ee3f/src/kendallc.cpp#L114

I sent a DM about this, but I think this is more "neat".

**Comment by rmflight** [comment]
Closed by a79ac753ff8c
